environment:
  GOOS: linux
  GOARCH: arm

build: off

before_test:
  - go version
  - go build mjpg-server.go

artifacts:
  - path: mjpg-server
    name: app

deploy:
- provider: BinTray
  username: speps
  api_key:
    secure: IkcYbqlqyL87MqKBJkcFI9j3aX42CKUmFxPcebrfEHr4EsQqcuHuZik9Zx8zRI6k
  subject: speps
  repo: grumpy-pi-mjpg
  package: latest
  version: official
  publish: true
  override: true
  artifact: app